/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ChatGPTShareToMarkdown
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/parser.ts
function extractEnqueueData(html) {
  const marker = 'streamController.enqueue("';
  const chunks = [];
  let searchStart = 0;
  while (true) {
    const idx = html.indexOf(marker, searchStart);
    if (idx < 0) break;
    const dataStart = idx + marker.length;
    let pos = dataStart;
    while (pos < html.length) {
      if (html[pos] === "\\") {
        pos += 2;
        continue;
      }
      if (html[pos] === '"') {
        break;
      }
      pos++;
    }
    if (pos < html.length) {
      chunks.push(html.substring(dataStart, pos));
      searchStart = pos + 1;
    }
  }
  if (chunks.length === 0) return null;
  return chunks.join("").replace(/\\"/g, '"').replace(/\\\\/g, "\\");
}
function extractSerializedData(html) {
  const combined = extractEnqueueData(html);
  if (!combined) return null;
  let depth = 0;
  let end = 0;
  for (let i = 0; i < combined.length; i++) {
    if (combined[i] === "[") depth++;
    else if (combined[i] === "]") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === 0) return null;
  try {
    return JSON.parse(combined.substring(0, end));
  } catch (e) {
    return null;
  }
}
function resolveValue(data, val, depth = 0) {
  if (depth > 50) return "<max depth>";
  if (val === null || val === void 0) return val;
  if (typeof val === "boolean") return val;
  if (typeof val === "string") return val;
  if (typeof val === "number") {
    if (val < 0) return null;
    if (val < data.length) {
      return resolveValue(data, data[val], depth + 1);
    }
    return val;
  }
  if (Array.isArray(val)) {
    return val.map((v) => resolveValue(data, v, depth + 1));
  }
  if (typeof val === "object") {
    const result = {};
    const obj = val;
    for (const [k, v] of Object.entries(obj)) {
      if (k.startsWith("_")) {
        const keyIdx = parseInt(k.substring(1), 10);
        if (keyIdx >= 0 && keyIdx < data.length) {
          const keyName = resolveValue(data, data[keyIdx], depth + 1);
          if (typeof keyName === "string") {
            result[keyName] = resolveValue(data, v, depth + 1);
          }
        }
      } else {
        result[k] = resolveValue(data, v, depth + 1);
      }
    }
    return result;
  }
  return val;
}
function parseSharedPage(html) {
  const data = extractSerializedData(html);
  if (!data) return null;
  const routeIdx = data.indexOf("routes/share.$shareId.($action)");
  if (routeIdx >= 0) {
    const routeRef = data[routeIdx + 1];
    if (routeRef && typeof routeRef === "object") {
      const resolved = resolveValue(data, routeRef);
      return resolved;
    }
  }
  const oldRouteIdx = data.indexOf("routes/s.$postId");
  if (oldRouteIdx >= 0) {
    const routeRef = data[oldRouteIdx + 1];
    if (routeRef && typeof routeRef === "object") {
      const resolved = resolveValue(data, routeRef);
      return resolved;
    }
  }
  return null;
}

// src/converter.ts
function convertToMarkdown(data) {
  var _a, _b;
  if ((_a = data.serverResponse) == null ? void 0 : _a.data) {
    return convertNewFormat(data);
  }
  const post = (_b = data.postWithProfile) == null ? void 0 : _b.post;
  if (!post) return "";
  const title = post.text || post.og_title || "ChatGPT Conversation";
  const lines = [];
  lines.push("---");
  lines.push(`title: "${escapeYaml(title)}"`);
  lines.push(`source: "${post.permalink || ""}"`);
  lines.push(`date: ${post.posted_at ? new Date(post.posted_at * 1e3).toISOString().split("T")[0] : ""}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${title}`);
  lines.push("");
  if (post.attachments) {
    for (const attachment of post.attachments) {
      const content = processAttachment(attachment, data);
      if (content) {
        lines.push(content);
      }
    }
  }
  return lines.join("\n");
}
function convertNewFormat(data) {
  var _a;
  const conversation = data.serverResponse.data;
  const title = conversation.title || "ChatGPT Conversation";
  const lines = [];
  lines.push("---");
  lines.push(`title: "${escapeYaml(title)}"`);
  lines.push(`source: "https://chatgpt.com/share/${data.sharedConversationId || ""}"`);
  lines.push(`date: ${conversation.create_time ? new Date(conversation.create_time * 1e3).toISOString().split("T")[0] : ""}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${title}`);
  lines.push("");
  const messages = extractMessagesFromMapping(conversation.mapping);
  for (const msg of messages) {
    const role = (_a = msg.author) == null ? void 0 : _a.role;
    let content = extractMessageContent(msg);
    if (!content) continue;
    content = ensureProperLineBreaks(content);
    if (role === "user") {
      lines.push("## User");
      lines.push("");
      lines.push(content);
      lines.push("");
    } else if (role === "assistant") {
      lines.push("## Assistant");
      lines.push("");
      lines.push(content);
      lines.push("");
    }
  }
  return lines.join("\n");
}
function extractMessagesFromMapping(mapping) {
  const messages = [];
  const root = mapping["client-created-root"];
  if (!root) return messages;
  function visit(nodeId) {
    var _a, _b;
    const node = mapping[nodeId];
    if (!node) return;
    if (node.message) {
      const role = (_a = node.message.author) == null ? void 0 : _a.role;
      const contentType = (_b = node.message.content) == null ? void 0 : _b.content_type;
      if ((role === "user" || role === "assistant") && (contentType === "text" || contentType === "code")) {
        messages.push(node.message);
      }
    }
    if (node.children) {
      for (const childId of node.children) {
        visit(childId);
      }
    }
  }
  if (root.children) {
    for (const childId of root.children) {
      visit(childId);
    }
  }
  return messages;
}
function escapeYaml(str) {
  return str.replace(/"/g, '\\"');
}
function processAttachment(attachment, _data) {
  switch (attachment.kind) {
    case "message_slice":
      return processMessageSlice(attachment.messages || []);
    case "deep_research":
      return processDeepResearch(attachment.messages || []);
    case "code_block":
      return processCodeBlock(attachment.content || "", attachment.language);
    case "media_generation":
      return `[Image]`;
    default:
      return null;
  }
}
function processMessageSlice(messages) {
  var _a;
  const lines = [];
  const conversationMessages = filterConversationMessages(messages);
  for (const msg of conversationMessages) {
    const role = (_a = msg.author) == null ? void 0 : _a.role;
    let content = extractMessageContent(msg);
    if (!content) continue;
    content = ensureProperLineBreaks(content);
    if (role === "user") {
      lines.push("## User");
      lines.push("");
      lines.push(content);
      lines.push("");
    } else if (role === "assistant") {
      lines.push("## Assistant");
      lines.push("");
      lines.push(content);
      lines.push("");
    }
  }
  return lines.join("\n");
}
function processDeepResearch(messages) {
  return processMessageSlice(messages);
}
function processCodeBlock(content, language) {
  const lang = language || "";
  return `\`\`\`${lang}
${content}
\`\`\``;
}
function filterConversationMessages(messages) {
  return messages.filter((msg) => {
    var _a, _b, _c;
    const role = (_a = msg.author) == null ? void 0 : _a.role;
    if (role === "user") return true;
    if (role === "assistant") {
      const contentType = (_b = msg.content) == null ? void 0 : _b.content_type;
      if (contentType === "code") {
        const text = ((_c = msg.content) == null ? void 0 : _c.text) || "";
        if (text.includes("system1_search_query")) return false;
        return true;
      }
      return true;
    }
    return false;
  });
}
function cleanCitations(text, msg) {
  var _a;
  let cleaned = text;
  const citationLinks = buildCitationLinkMap(((_a = msg.metadata) == null ? void 0 : _a.content_references) || []);
  for (const [marker, link] of citationLinks) {
    if (isCitationRefId(marker)) continue;
    cleaned = cleaned.replace(
      new RegExp(escapeRegExp(marker), "g"),
      formatInlineCitationLink(link)
    );
  }
  cleaned = cleaned.replace(
    /citation:(turn\d+search\d+)/g,
    (_match, refId) => {
      const link = citationLinks.get(refId);
      return link ? formatInlineCitationLink(link) : "";
    }
  );
  cleaned = cleaned.replace(
    /\uFFFDcite\uFFFD(turn\d+search\d+)\uFFFD/g,
    (_match, refId) => {
      const link = citationLinks.get(refId);
      return link ? formatInlineCitationLink(link) : "";
    }
  );
  cleaned = cleaned.replace(
    /\u3000cite\u3002(turn\d+search\d+)\u3001/g,
    (_match, refId) => {
      const link = citationLinks.get(refId);
      return link ? formatInlineCitationLink(link) : "";
    }
  );
  return cleaned.replace(/[ \t]+/g, " ").trim();
}
function buildCitationLinkMap(references) {
  const links = /* @__PURE__ */ new Map();
  for (const reference of references) {
    const matchedText = reference.matched_text;
    const link = getReferenceMarkdownLink(reference);
    if (!matchedText || !link) continue;
    links.set(matchedText, link);
    const refId = extractCitationRefId(matchedText);
    if (refId) {
      links.set(refId, link);
    }
  }
  return links;
}
function formatInlineCitationLink(link) {
  return ` ${link}`;
}
function getReferenceMarkdownLink(reference) {
  var _a, _b, _c;
  const alt = (_a = reference.alt) == null ? void 0 : _a.trim();
  if (alt) {
    return stripOuterParentheses(alt);
  }
  const item = (_b = reference.items) == null ? void 0 : _b.find((entry) => entry.url);
  const url = (item == null ? void 0 : item.url) || ((_c = reference.safe_urls) == null ? void 0 : _c[0]);
  if (!url) return null;
  const title = (item == null ? void 0 : item.attribution) || (item == null ? void 0 : item.title) || url;
  return `[${escapeMarkdownLinkText(title)}](${url})`;
}
function stripOuterParentheses(text) {
  const match = text.match(/^\((\[[^\]]+\]\([^)]+\))\)$/);
  return match ? match[1] : text;
}
function extractCitationRefId(text) {
  const match = text.match(/turn\d+search\d+/);
  return match ? match[0] : null;
}
function isCitationRefId(text) {
  return /^turn\d+search\d+$/.test(text);
}
function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function escapeMarkdownLinkText(text) {
  return text.replace(/([\\\]])/g, "\\$1");
}
function extractMessageContent(msg) {
  const content = msg.content;
  if (!content) return null;
  if (content.content_type === "text") {
    const parts = content.parts;
    if (Array.isArray(parts)) {
      const cleaned = parts.filter((p) => p && p.trim()).map((p) => cleanCitations(p, msg));
      return cleaned.join("\n\n");
    }
    return null;
  }
  if (content.content_type === "code") {
    const text = content.text || "";
    if (text.includes("system1_search_query")) return null;
    const lang = content.language || "";
    return `\`\`\`${lang}
${text}
\`\`\``;
  }
  return null;
}
function ensureProperLineBreaks(text) {
  return text.replace(/\n{3,}/g, "\n\n").replace(/([^\n])\n([^\n])/g, "$1\n\n$2");
}

// src/main.ts
var import_obsidian2 = require("obsidian");
var CHATGPT_SHARE_REGEX = /https?:\/\/chatgpt\.com\/(?:s|share)\/([a-zA-Z0-9_-]+)/;
var ChatGPTShareToMarkdown = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("download", "ChatGPT Share Importer", () => {
      this.importWithUrlInput();
    });
    this.addCommand({
      id: "import-chatgpt-share",
      name: "Import ChatGPT shared link",
      callback: () => this.importFromClipboard()
    });
    this.addCommand({
      id: "import-chatgpt-share-url",
      name: "Import ChatGPT shared link (enter URL)",
      callback: () => this.importWithUrlInput()
    });
    this.registerEvent(
      this.app.workspace.on("editor-paste", (evt, _editor, info) => {
        const infoAny = info;
        const plain = infoAny == null ? void 0 : infoAny.plain;
        if (plain) {
          const url = plain.trim();
          if (CHATGPT_SHARE_REGEX.test(url)) {
            evt.preventDefault();
            this.importFromUrl(url);
          }
        }
      })
    );
  }
  async importFromClipboard() {
    try {
      const text = await navigator.clipboard.readText();
      const url = text.trim();
      if (!CHATGPT_SHARE_REGEX.test(url)) {
        new import_obsidian.Notice("Clipboard does not contain a valid ChatGPT shared link");
        return;
      }
      await this.importFromUrl(url);
    } catch (e) {
      new import_obsidian.Notice("Failed to read clipboard");
    }
  }
  async importWithUrlInput() {
    const modal = new UrlInputModal(this.app, async (url) => {
      await this.importFromUrl(url);
    });
    modal.open();
  }
  async importFromUrl(url) {
    var _a, _b, _c, _d, _e, _f;
    const match = url.match(CHATGPT_SHARE_REGEX);
    if (!match) {
      new import_obsidian.Notice("Invalid ChatGPT shared link format");
      return;
    }
    const postId = match[1];
    new import_obsidian.Notice("Fetching conversation...");
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET"
      });
      const html = response.text;
      const data = parseSharedPage(html);
      if (!data) {
        new import_obsidian.Notice("Failed to parse conversation data");
        return;
      }
      if ((_a = data.serverResponse) == null ? void 0 : _a.error) {
        new import_obsidian.Notice(`Error: ${data.serverResponse.error}`);
        return;
      }
      if (!data.postWithProfile && !((_b = data.serverResponse) == null ? void 0 : _b.data)) {
        new import_obsidian.Notice("Failed to parse conversation data");
        return;
      }
      const markdown = convertToMarkdown(data);
      const title = ((_d = (_c = data.serverResponse) == null ? void 0 : _c.data) == null ? void 0 : _d.title) || ((_f = (_e = data.postWithProfile) == null ? void 0 : _e.post) == null ? void 0 : _f.text) || postId;
      const filename = sanitizeFilename(title) + ".md";
      const vault = this.app.vault;
      const filePath = filename;
      const existingFile = vault.getAbstractFileByPath(filePath);
      if (existingFile) {
        new import_obsidian.Notice(`File "${filename}" already exists`);
        return;
      }
      await vault.create(filePath, markdown);
      new import_obsidian.Notice(`Saved as "${filename}"`);
      const file = vault.getAbstractFileByPath(filePath);
      if (file) {
        await this.app.workspace.openLinkText(filePath, "", false);
      }
    } catch (err) {
      console.error("Failed to import ChatGPT share:", err);
      new import_obsidian.Notice("Failed to fetch or parse the shared link");
    }
  }
};
function sanitizeFilename(name) {
  return name.replace(/[<>:"/\\|?*]/g, "_").replace(/\s+/g, " ").trim().substring(0, 200);
}
var UrlInputModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.url = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter ChatGPT shared link" });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "https://chatgpt.com/share/...",
      cls: "chatgpt-url-input"
    });
    inputEl.style.width = "100%";
    inputEl.style.marginTop = "10px";
    inputEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        this.url = inputEl.value.trim();
        if (this.url) {
          this.onSubmit(this.url);
          this.close();
        }
      }
    });
    const btnContainer = contentEl.createEl("div");
    btnContainer.style.marginTop = "15px";
    btnContainer.style.display = "flex";
    btnContainer.style.justifyContent = "flex-end";
    btnContainer.style.gap = "10px";
    const cancelBtn = btnContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const submitBtn = btnContainer.createEl("button", { text: "Import", cls: "mod-cta" });
    submitBtn.addEventListener("click", () => {
      this.url = inputEl.value.trim();
      if (this.url) {
        this.onSubmit(this.url);
        this.close();
      }
    });
    inputEl.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
